language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install -q flake8 coveralls coverage
  - python setup.py install

before_script:
  - make flake8

script:
  - make coverage

after_success:
  - make coveralls
